routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->middleware('verified');
Route::group(['middleware' => ['auth', 'checkRole:admin']], function () {
    Route::resource('agamas', 'AgamaController');
    Route::resource('diklats', 'DiklatController');
    Route::resource('gapoks', 'GapokController');
    Route::resource('jabatanStrukturals', 'Jabatan_StrukturalController');
    Route::resource('jabatanFunsionals', 'Jabatan_FunsionalController');
    Route::resource('jabatanTambahans', 'Jabatan_TambahanController');
    Route::resource('pendidikans', 'PendidikanController');
    Route::resource('pegawais', 'PegawaiController');
    Route::resource('pelanggarans', 'PelanggaranController');
    Route::resource('tindakans', 'TindakanController');
    Route::resource('pelanggaranPegawais', 'Pelanggaran_PegawaiController');
    Route::resource('absensis', 'AbsensiController');
    Route::resource('cutis','CutiController');
    Route::get('absensis/cari', function () {
        return view('welcome');
    });
    Route::resource('penggajianPegawais', 'PenggajianPegawaiController');
    Route::resource('jabatanPegawais', 'JabatanPegawaiController');
    Route::resource('diklatPegawais', 'DiklatPegawaiController');
    Route::get('admin/cuti','UserController@cutiAccTampil');
    Route::post('admin/cuti/acc','UserController@cutiAccUpdate');

});
// user

Route::group(['middleware' => ['auth', 'checkRole:pegawai']], function () {
    Route::get('/users', ['as' => 'user_profile.index', 'uses' => 'UserController@profile']);
    Route::get('/users/profil', ['as' => 'user_profile.index', 'uses' => 'UserController@profile']);
    Route::get('/users/absensi', ['as' => 'user_absensi.index', 'uses' => 'UserController@absensi']);
    Route::get('/users/gaji', ['as' => 'user_gaji.index', 'uses' => 'UserController@gaji']);
    Route::get('/users/pelanggaran', ['as' => 'user_pelanggaran.index', 'uses' => 'UserController@pelanggaran']);
    Route::get('/users/jabatan', ['as' => 'user_jabatan.index', 'uses' => 'UserController@jabatan']);
    Route::get('/users/diklat', ['as' => 'user_diklat.index', 'uses' => 'UserController@diklat']);
    Route::get('/users/cuti', ['as' => 'user_cuti.index', 'uses' => 'UserController@cuti']);
    Route::get('/users/cuti/create', ['as' => 'user_cuti.create', 'uses' => 'UserController@cutiCreate']);
    Route::post('/users/cuti/store', ['as' => 'user_cuti.store', 'uses' => 'UserController@cutiStore']);
    Route::get('/users/cuti/show/{id}', ['as' => 'user_cuti.show', 'uses' => 'UserController@cutiShow']);
    Route::get('/users/cuti/edit/{id}', ['as' => 'user_cuti.edit', 'uses' => 'UserController@cutiEdit']);
    Route::patch('/users/cuti/update/{id}', ['as' => 'user_cuti.update', 'uses' => 'UserController@cutiUpdate']);
    Route::delete('/users/cuti/destroy/{id}', ['as' => 'user_cuti.destroy', 'uses' => 'UserController@cutiDestroy']);
});

app/Models/Pegawai.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Pegawai
 * @package App\Models
 * @version March 19, 2020, 5:53 am UTC
 *
 * @property string nip
 * @property string nama
 * @property string password
 * @property string tempat
 * @property string tgl_lahir
 * @property string telp
 * @property string jenis_kelamin
 * @property string status_pegawai
 * @property string foto
 * @property integer id_agama
 * @property string hobi
 * @property integer id_pendidikan
 * @property string nama_sekolah
 * @property string tahun_sttb
 * @property string gelar_depan
 * @property string gelar_belakang
 * @property string status_pernikahan
 */
class Pegawai extends Model
{
    use SoftDeletes;

    public $table = 'pegawais';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'id_user',
        'nip',
        'nama',
        'password',
        'tempat',
        'tgl_lahir',
        'telp',
        'jenis_kelamin',
        'status_pegawai',
        'foto',
        'id_agama',
        'hobi',
        'id_pendidikan',
        'nama_sekolah',
        'tahun_sttb',
        'gelar_depan',
        'gelar_belakang',
        'status_pernikahan',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nip' => 'string',
        'nama' => 'string',
        'password' => 'string',
        'tempat' => 'string',
        'tgl_lahir' => 'string',
        'telp' => 'string',
        'jenis_kelamin' => 'string',
        'status_pegawai' => 'string',
        'foto' => 'string',
        'id_agama' => 'integer',
        'hobi' => 'string',
        'id_pendidikan' => 'integer',
        'nama_sekolah' => 'string',
        'tahun_sttb' => 'string',
        'gelar_depan' => 'string',
        'gelar_belakang' => 'string',
        'status_pernikahan' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nip' => 'required:numeric',
        'nama' => 'required',
        'password' => 'required',
        'tempat' => 'required',
        'tgl_lahir' => 'required',
        'telp' => 'required:numeric',
        'jenis_kelamin' => 'required',
        'status_pegawai' => 'required',
        'foto' => 'required|file|image|mimes:jpeg,png,jpg|max:2048',
        'id_agama' => 'required',
        'hobi' => 'required',
        'id_pendidikan' => 'required',
        'nama_sekolah' => 'required',
        'tahun_sttb' => 'required',
        'gelar_depan' => 'required',
        'gelar_belakang' => 'required',
        'status_pernikahan' => 'required'
    ];
    public function agama()
    {
        return $this->hasOne(Agama::class, 'id', 'id_agama');
    }
    public function pendidikan()
    {
        return $this->hasOne(Pendidikan::class, 'id', 'id_pendidikan');
    }
    public function diklat()
    {
            return $this->hasOne(Diklat::class, 'id', 'id_diklat');
    }
    public function struktural()
    {
            return $this->hasOne(Jabatan_Struktural::class, 'id', 'id_struktural');
    }
    public function fungsional()
    {
            return $this->hasOne(Jabatan_Funsional::class, 'id', 'id_fungsional');
    }
    public function tambahan()
    {
        return $this->hasOne(Jabatan_Tambahan::class, 'id', 'id_tambahan');
    }
    public function Gapok()
    {
            return $this->hasOne(Gapok::class, 'id', 'gapok');
    }
    public function pelanggaran()
    {
            return $this->hasOne(Pelanggaran::class, 'id', 'pelanggaran');
    }
    public function tindakan()
    {
            return $this->hasOne(Tindakan::class, 'id', 'tindakan');
    }

    public function users(){
        return $this->hasOne(User::class, 'id', 'user_id');
    }


}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePegawaiRequest;
use App\Http\Requests\UpdatePegawaiRequest;
use App\Repositories\PegawaiRepository;
use App\Repositories\JabatanPegawaiRepository;
use App\Repositories\AgamaRepository;
use App\Repositories\PendidikanRepository;
use App\Http\Controllers\AppBaseController;
use App\Repositories\PenggajianPegawaiRepository;
use App\Repositories\Pelanggaran_PegawaiRepository;
use App\Repositories\DiklatPegawaiRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\User;
use Flash;
use Response;
use Illuminate\Support\Facades\DB;


class PegawaiController extends AppBaseController
{
    /** @var  PegawaiRepository */
    private $pegawaiRepository;
    private $agamaRepository;
    private $pendidikanRepository;
    private $jabatanPegawaiRepository;
    private $penggajianPegawaiRepository;
    private $pelanggaranPegawaiRepository;
    private $diklatPegawaiRepository;

    public function __construct(DiklatPegawaiRepository $diklatPegawaiRepo, Pelanggaran_PegawaiRepository $pelanggaranPegawaiRepo, PenggajianPegawaiRepository $penggajianPegawaiRepo, JabatanPegawaiRepository $jabatanPegawaiRepo, PegawaiRepository $pegawaiRepo, AgamaRepository $agamaRepo, PendidikanRepository $pendidikanRepo)
    {
        $this->pegawaiRepository = $pegawaiRepo;
        $this->agamaRepository = $agamaRepo;
        $this->pendidikanRepository = $pendidikanRepo;
        $this->jabatanPegawaiRepository = $jabatanPegawaiRepo;
        $this->penggajianPegawaiRepository = $penggajianPegawaiRepo;
        $this->pelanggaranPegawaiRepository = $pelanggaranPegawaiRepo;
        $this->diklatPegawaiRepository = $diklatPegawaiRepo;
    }

    /**
     * Display a listing of the Pegawai.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $pegawais = $this->pegawaiRepository->all();

        return view('pegawais.index')
            ->with('pegawais', $pegawais);
    }

    /**
     * Show the form for creating a new Pegawai.
     *
     * @return Response
     */
    public function create()
    {

        $agama = $this->agamaRepository->all()->pluck('agama','id');
        $pendidikan = $this->pendidikanRepository->all()->pluck('pendidikan','id');
        return view('pegawais.create',compact(['agama', 'pendidikan']));
    }

    /**
     * Store a newly created Pegawai in storage.
     *
     * @param CreatePegawaiRequest $request
     *
     * @return Response
     */
    public function store(CreatePegawaiRequest $request)
    {
        $user = new User;
        $user->role = 'pegawai';
        $user->name = $request->nama;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->remember_token = Str::random(60);
        $user->save();

        $request->request->add(['user_id' => $user->id]);
        // $peg = $this->pegawaiRepository->create($request->all());
        $file = $request->file('foto');
        $tujuan_upload = 'data_file/img';
        $nama_file = time();
        $file->move($tujuan_upload, $nama_file);

        $pegawai = $this->pegawaiRepository->create([
        'id_user'=>$request->user_id,
        'nip' => $request->nip,
        'nama' => $request->nama,
        'password' => $request->password,
        'tempat' => $request->tempat,
        'tgl_lahir' => $request->tgl_lahir,
        'telp' => $request->telp,
        'jenis_kelamin' => $request->jenis_kelamin,
        'status_pegawai' => $request->status_pegawai,
        'foto' => $nama_file,
        'id_agama' => $request->id_agama,
        'hobi' => $request->hobi,
        'id_pendidikan' => $request->id_pendidikan,
        'nama_sekolah' => $request->nama_sekolah,
        'tahun_sttb' => $request->tahun_sttb,
        'gelar_depan' => $request->gelar_depan,
        'gelar_belakang' => $request->gelar_belakang,
        'status_pernikahan' => $request->status_pernikahan]
        );
        Flash::success('Pegawai saved successfully.');

        return redirect(route('pegawais.index'));
    }

    /**
     * Display the specified Pegawai.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $pegawai = $this->pegawaiRepository->find($id);
        $jabatanPegawais = $this->jabatanPegawaiRepository->all()->where('id_pegawai', "=", $id);
        $penggajianPegawais = $this->penggajianPegawaiRepository->all()->where('id_pegawai', "=", $id);
        $pelanggaranPegawais = $this->pelanggaranPegawaiRepository->all()->where('id_pegawai', "=", $id);
        $diklatPegawais = $this->diklatPegawaiRepository->all()->where('id_pegawai', "=", $id);


        if (empty($pegawai)) {
            Flash::error('Pegawai not found');

            return redirect(route('pegawais.index'));
        }

        return view('pegawais.show', ['diklatPegawais' => $diklatPegawais, 'pelanggaranPegawais' => $pelanggaranPegawais, 'pegawai' => $pegawai, 'jabatanPegawais' => $jabatanPegawais, 'penggajianPegawai' => $penggajianPegawais]);
    }

    /**
     * Show the form for editing the specified Pegawai.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $pegawai = $this->pegawaiRepository->find($id);

        if (empty($pegawai)) {
            Flash::error('Pegawai not found');

            return redirect(route('pegawais.index'));
        }

        return view('pegawais.edit')->with('pegawai', $pegawai);
    }

    /**
     * Update the specified Pegawai in storage.
     *
     * @param int $id
     * @param UpdatePegawaiRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePegawaiRequest $request)
    {
        $pegawai = $this->pegawaiRepository->find($id);

        if (empty($pegawai)) {
            Flash::error('Pegawai not found');

            return redirect(route('pegawais.index'));
        }

        $pegawai = $this->pegawaiRepository->update($request->all(), $id);

        Flash::success('Pegawai updated successfully.');

        return redirect(route('pegawais.index'));
    }

    /**
     * Remove the specified Pegawai from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $pegawai = $this->pegawaiRepository->find($id);

        if (empty($pegawai)) {
            Flash::error('Pegawai not found');

            return redirect(route('pegawais.index'));
        }

        $this->pegawaiRepository->delete($id);

        Flash::success('Pegawai deleted successfully.');

        return redirect(route('pegawais.index'));
    }

    public function profile()
    {
        return view('user_profile.index');
    }
}

resources/views/pegawais/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('pegawais.index') !!}">Pegawai</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Pegawai</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'pegawais.store', 'files' => true]) !!}

                                   @include('pegawais.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/pegawais/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('pegawais.index') !!}">Pegawai</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Pegawai</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($pegawai, ['route' => ['pegawais.update', $pegawai->id], 'method' => 'patch', 'files' => true]) !!}

                              @include('pegawais.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/pegawais/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Pegawais</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Pegawais
                             <a class="pull-right" href="{{ route('pegawais.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('pegawais.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/pegawais/show.blade.php
@extends('layouts.app')
<style>
    label {
        color:grey;
       }
</style>
@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('pegawais.index') }}">Pegawai</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('pegawais.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                <center>
                                    <!-- Foto Field -->
                                    <div class="form-group">
                                        <img width="150px" src="{{ url('/data_file/img/'.$pegawai->foto) }}">
                                    </div>
                                <center>
                                <div class="row">
                                    @include('pegawais.show_fields')
                                 </div>
                            </div>
                         </div>
                         <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                              <a class="nav-link active" id="jabatan-tab" data-toggle="tab" href="#jabatan" role="tab" aria-controls="jabatan" aria-selected="true">Jabatan</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" id="diklat-tab" data-toggle="tab" href="#diklat" role="tab" aria-controls="diklat" aria-selected="false">Diklat</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" id="hukuman-tab" data-toggle="tab" href="#hukuman" role="tab" aria-controls="hukuman" aria-selected="false">Hukuman</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" id="Gaji-tab" data-toggle="tab" href="#Gaji" role="tab" aria-controls="Gaji" aria-selected="false">Gaji</a>
                            </li>
                          </ul>
                          <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="jabatan" role="tabpanel" aria-labelledby="jabatan-tab">
                                <div class="table-responsive-sm">
                                    <table class="table table-striped" id="jabatanPegawais-table">
                                        <thead>
                                            <tr>
                                                <th>Id Struktural</th>
                                                <th>Id Fungsional</th>
                                                <th>Id Tambahan</th>
                                                <th colspan="3">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($jabatanPegawais as $jabatanPegawai)
                                            <tr>
                                                <td>{{ $jabatanPegawai->struktural->jabatan_struktural }}</td>
                                                <td>{{ $jabatanPegawai->fungsional->jabatan_fungsional }}</td>
                                                <td>{{ $jabatanPegawai->tambahan->jabatan_tambahan }}</td>
                                                <td>
                                                    {!! Form::open(['route' => ['jabatanPegawais.destroy', $jabatanPegawai->id], 'method' => 'delete']) !!}
                                                    <div class='btn-group'>
                                                        <a href="{{ route('jabatanPegawais.show', [$jabatanPegawai->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                                                        <a href="{{ route('jabatanPegawais.edit', [$jabatanPegawai->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="diklat" role="tabpanel" aria-labelledby="diklat-tab">
                                <div class="table-responsive-sm">
                                    <table class="table table-striped" id="diklatPegawais-table">
                                        <thead>
                                            <tr>
                                                <th>Id Diklat</th>
                                                <th colspan="3">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($diklatPegawais as $diklatPegawai)
                                            <tr>
                                                <td>{{$diklatPegawai->diklat->jenis_diklat }}</td>
                                                <td>
                                                    {!! Form::open(['route' => ['diklatPegawais.destroy', $diklatPegawai->id], 'method' => 'delete']) !!}
                                                    <div class='btn-group'>
                                                        <a href="{{ route('diklatPegawais.show', [$diklatPegawai->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                                                        <a href="{{ route('diklatPegawais.edit', [$diklatPegawai->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="hukuman" role="tabpanel" aria-labelledby="hukuman-tab">
                                <div class="table-responsive-sm">
                                    <table class="table table-striped" id="pelanggaranPegawais-table">
                                        <thead>
                                            <tr>
                                                <th>Pelanggaran</th>
                                                <th>Tindakan</th>
                                                <th>Keterangan</th>
                                                <th colspan="3">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($pelanggaranPegawais as $pelanggaranPegawai)
                                            <tr>
                                                <td>{{ $pelanggaranPegawai->Pelanggaran->pelanggaran }}</td>
                                                <td>{{ $pelanggaranPegawai->Tindakan->tindakan }}</td>
                                                <td>{{ $pelanggaranPegawai->keterangan }}</td>
                                                <td>
                                                    {!! Form::open(['route' => ['pelanggaranPegawais.destroy', $pelanggaranPegawai->id], 'method' => 'delete']) !!}
                                                    <div class='btn-group'>
                                                        <a href="{{ route('pelanggaranPegawais.show', [$pelanggaranPegawai->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                                                        <a href="{{ route('pelanggaranPegawais.edit', [$pelanggaranPegawai->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="Gaji" role="tabpanel" aria-labelledby="Gaji-tab">
                                @foreach ( $penggajianPegawai as  $penggajianPegawai )
                                <!-- Gapok Field -->
                                <div class="form-group">
                                    {!! Form::label('gapok', 'Gapok:') !!}
                                    <p>{{ $penggajianPegawai->Gapok->nominal_gaji }}</p>
                                </div>

                                <!-- Gaji Tambahan Field -->
                                <div class="form-group">
                                    {!! Form::label('gaji_tambahan', 'Gaji Tambahan:') !!}
                                    <p>{{ $penggajianPegawai->gaji_tambahan }}</p>
                                </div>

                                <!-- Gaji Total Field -->
                                <div class="form-group">
                                    {!! Form::label('gaji_total', 'Gaji Total:') !!}
                                    <p>{{ $penggajianPegawai->gaji_total }}</p>
                                </div>
                                @endforeach
                            </div>
                          </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/pegawais/show_fields.blade.php
<div class="col-md-3">
    <!-- Nip Field -->
    <div class="form-group">
        {!! Form::label('nip', 'Nip:') !!}
        <p>{{ $pegawai->nip }}</p>
    </div>

    <!-- Nama Field -->
    <div class="form-group">
        {!! Form::label('nama', 'Nama:') !!}
        <p>{{ $pegawai->gelar_depan }} {{ $pegawai->nama }} {{ $pegawai->gelar_belakang }}</p>
    </div>

    <!-- Email Field -->
    <div class="form-group">
        {!! Form::label('email', 'Email:') !!}
        <p>{{ $pegawai->email }}</p>
    </div>

    <!-- Password Field -->
    <div class="form-group">
        {!! Form::label('password', 'Password:') !!}
        <p>{{ $pegawai->password }}</p>
    </div>
    <!-- Telp Field -->
    <div class="form-group">
        {!! Form::label('telp', 'Telp:') !!}
        <p>{{ $pegawai->telp }}</p>
    </div>
</div>

<div class="col-md-3">
    <!-- Tempat Field -->
    <div class="form-group">
        {!! Form::label('tempat', 'Tempat/Tgl Lahir:') !!}
        <p>{{ $pegawai->tempat }}/{{ $pegawai->tgl_lahir }}</p>
    </div>


<!-- Jenis Kelamin Field -->
<div class="form-group">
    {!! Form::label('jenis_kelamin', 'Jenis Kelamin:') !!}
    <p>{{ $pegawai->jenis_kelamin }}</p>
</div>

<!-- Status Pegawai Field -->
<div class="form-group">
    {!! Form::label('status_pegawai', 'Status Pegawai:') !!}
    <p>{{ $pegawai->status_pegawai }}</p>
</div>
<!-- Id Agama Field -->
<div class="form-group">
    {!! Form::label('id_agama', 'Agama:') !!}
    <p>{{ $pegawai->agama->agama }}</p>
</div>
</div>
<div class="col-md-3">


<!-- Hobi Field -->
<div class="form-group">
    {!! Form::label('hobi', 'Hobi:') !!}
    <p>{{ $pegawai->hobi }}</p>
</div>

<!-- Id Pendidikan Field -->
<div class="form-group">
    {!! Form::label('id_pendidikan', 'Pendidikan Terakhir:') !!}
    <p>{{ $pegawai->pendidikan->pendidikan }}</p>
</div>

<!-- Nama Sekolah Field -->
<div class="form-group">
    {!! Form::label('nama_sekolah', 'Nama Sekolah:') !!}
    <p>{{ $pegawai->nama_sekolah }}</p>
</div>
<!-- Tahun Sttb Field -->
    <div class="form-group">
        {!! Form::label('tahun_sttb', 'Tahun Sttb:') !!}
        <p>{{ $pegawai->tahun_sttb }}</p>
    </div>
</div>
<div class="col-md-3">
<!-- Status Pernikahan Field -->
    <div class="form-group">
        {!! Form::label('status_pernikahan', 'Status Pernikahan:') !!}
        <p>{{ $pegawai->status_pernikahan }}</p>
    </div>
    <!-- Created At Field -->
    <div class="form-group">
        {!! Form::label('created_at', 'Tanggal Masuk:') !!}
        <p>{{ $pegawai->created_at }}</p>
    </div>
    <!-- Updated At Field -->
    <div class="form-group">
        {!! Form::label('updated_at', 'Updated At:') !!}
        <p>{{ $pegawai->updated_at }}</p>
    </div>
</div>